# Generated by Django 5.2.17 on 2026-08-09 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode', models.CharField(max_length=10, verbose_name='méthode HTTP')),
                ('chemin', models.CharField(db_index=True, max_length=300, verbose_name='chemin')),
                ('statut', models.IntegerField(verbose_name='statut HTTP')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='adresse IP')),
                ('agent', models.CharField(blank=True, default='', max_length=400, verbose_name='user-agent')),
                ('geolocalisation', models.JSONField(blank=True, help_text='Dérivée de la base GeoLite2 (pays, ville, coordonnées).', null=True, verbose_name='géolocalisation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date')),
                ('utilisateur', models.ForeignKey(blank=True, help_text='Utilisateur identifié par son jeton JWT (null si anonyme).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_actions', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'action journalisée',
                'verbose_name_plural': 'actions journalisées',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', '-date_creation'], name='core_journa_utilisa_20b062_idx')],
            },
        ),
    ]
