# Generated by Django 5.2.17 on 2026-08-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalaction',
            options={'ordering': ('-date_creation',), 'verbose_name': 'action journalisée', 'verbose_name_plural': 'actions journalisées'},
        ),
    ]
