# Generated by Django 5.2.17 on 2026-08-08 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteCommentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.IntegerField(choices=[(1, 'Vote positif'), (-1, 'Vote négatif')], default=1, help_text='+1 pour un vote positif, -1 pour un vote négatif.', verbose_name='valeur du vote')),
                ('date_vote', models.DateTimeField(auto_now_add=True, verbose_name='date du vote')),
                ('commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='comments.commentaire', verbose_name='commentaire')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'vote de commentaire',
                'verbose_name_plural': 'votes de commentaires',
                'ordering': ['-date_vote'],
                'unique_together': {('utilisateur', 'commentaire')},
            },
        ),
        migrations.CreateModel(
            name='VotePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.IntegerField(choices=[(1, 'Vote positif'), (-1, 'Vote négatif')], default=1, help_text='+1 pour un vote positif, -1 pour un vote négatif.', verbose_name='valeur du vote')),
                ('date_vote', models.DateTimeField(auto_now_add=True, verbose_name='date du vote')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='posts.post', verbose_name='post')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'vote de post',
                'verbose_name_plural': 'votes de posts',
                'ordering': ['-date_vote'],
                'unique_together': {('utilisateur', 'post')},
            },
        ),
    ]
