# Generated by Django 5.2.17 on 2026-08-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votecommentaire',
            options={'ordering': ('-date_vote',), 'verbose_name': 'vote de commentaire', 'verbose_name_plural': 'votes de commentaires'},
        ),
        migrations.AlterModelOptions(
            name='votepost',
            options={'ordering': ('-date_vote',), 'verbose_name': 'vote de post', 'verbose_name_plural': 'votes de posts'},
        ),
    ]
