# Generated by Django 5.2.17 on 2026-08-08 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.TextField(verbose_name='raison du signalement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date du signalement')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('resolu', 'Résolu'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='statut')),
            ],
            options={
                'verbose_name': 'signalement',
                'verbose_name_plural': 'signalements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Moderateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('moderateur', 'Modérateur'), ('administrateur', 'Administrateur')], default='moderateur', max_length=20, verbose_name='rôle')),
                ('date_nomination', models.DateTimeField(auto_now_add=True, verbose_name='date de nomination')),
                ('communaute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderateurs', to='communities.communaute', verbose_name='communauté')),
            ],
            options={
                'verbose_name': 'modérateur',
                'verbose_name_plural': 'modérateurs',
                'ordering': ['date_nomination'],
            },
        ),
    ]
