# Generated by Django 5.2.17 on 2026-08-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_abonnement', models.DateTimeField(auto_now_add=True, verbose_name="date d'abonnement")),
            ],
            options={
                'verbose_name': 'abonnement',
                'ordering': ['-date_abonnement'],
            },
        ),
        migrations.CreateModel(
            name='Communaute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.SlugField(help_text='Identifiant unique de la communauté (ex : tech-afrique).', unique=True, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image_url', models.URLField(blank=True, verbose_name="URL de l'image de couverture")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
            ],
            options={
                'verbose_name': 'communauté',
                'verbose_name_plural': 'communautés',
                'ordering': ['-date_creation'],
            },
        ),
    ]
