# Generated by Django 5.2.17 on 2026-08-08 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AddField(
            model_name='communaute',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communautes_crees', to=settings.AUTH_USER_MODEL, verbose_name='créateur'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='communaute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='communities.communaute', verbose_name='communauté'),
        ),
        migrations.AlterUniqueTogether(
            name='abonnement',
            unique_together={('utilisateur', 'communaute')},
        ),
    ]
