# Generated by Django 5.2.17 on 2026-08-09 08:04

from django.db import migrations, models

import core.validateurs


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communaute',
            name='banniere',
            field=models.ImageField(blank=True, help_text='Bannière importée (JPG, PNG, GIF, WebP, 5 Mo max).', upload_to='communautes/', validators=[core.validateurs.valider_image_upload], verbose_name='bannière'),
        ),
    ]
