# Generated by Django 5.2.17 on 2026-08-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_communaute_banniere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abonnement',
            options={'ordering': ('-date_abonnement',), 'verbose_name': 'abonnement'},
        ),
        migrations.AlterModelOptions(
            name='communaute',
            options={'ordering': ('-date_creation',), 'verbose_name': 'communauté', 'verbose_name_plural': 'communautés'},
        ),
    ]
