# Generated by Django 5.2.17 on 2026-08-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('score', models.IntegerField(default=0, help_text='Somme des votes (mise à jour par signaux).', verbose_name='score')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
            ],
            options={
                'verbose_name': 'commentaire',
                'verbose_name_plural': 'commentaires',
                'ordering': ['date_creation'],
            },
        ),
    ]
