# Generated by Django 5.2.17 on 2026-08-08 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL, verbose_name='auteur'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='commentaire_parent',
            field=models.ForeignKey(blank=True, help_text='Commentaire auquel cette réponse est attachée (null = racine).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='comments.commentaire', verbose_name='commentaire parent'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='posts.post', verbose_name='post'),
        ),
    ]
