# Generated by Django 5.2.17 on 2026-08-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaire',
            options={'ordering': ('date_creation',), 'verbose_name': 'commentaire', 'verbose_name_plural': 'commentaires'},
        ),
    ]
