# Generated by Django 5.2.17 on 2026-08-09 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verifie',
            field=models.BooleanField(default=False, help_text='Passe à True après validation du lien envoyé par e-mail.', verbose_name='e-mail vérifié'),
        ),
        migrations.CreateModel(
            name='EchecConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clef', models.CharField(max_length=64, verbose_name='clé de verrouillage (username ou IP)')),
                ('horodatage', models.DateTimeField(auto_now_add=True, verbose_name='horodatage')),
            ],
            options={
                'verbose_name': 'échec de connexion',
                'verbose_name_plural': 'échecs de connexion',
                'indexes': [models.Index(fields=['clef', 'horodatage'], name='users_echec_clef_1b2090_idx')],
            },
        ),
        migrations.CreateModel(
            name='JetonSecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('but', models.CharField(choices=[('verification', "Vérification d'e-mail"), ('reset_mot_de_passe', 'Réinitialisation du mot de passe')], max_length=30, verbose_name='but')),
                ('jeton_hache', models.CharField(max_length=64, verbose_name='jeton haché (SHA-256)')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('expire_le', models.DateTimeField(verbose_name='expire le')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jetons_securite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'jeton de sécurité',
                'verbose_name_plural': 'jetons de sécurité',
                'indexes': [models.Index(fields=['but', 'utilisateur'], name='users_jeton_but_605dd7_idx')],
            },
        ),
    ]
