# Generated by Django 5.2.17 on 2026-08-09 08:04

from django.db import migrations, models

import core.validateurs


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verifie_echecconnexion_jetonsecurite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Avatar importé (JPG, PNG, GIF, WebP, 5 Mo max).', upload_to='avatars/', validators=[core.validateurs.valider_image_upload], verbose_name='avatar'),
        ),
    ]
