# Generated by Django 5.2.17 on 2026-08-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-karma', 'username'), 'verbose_name': 'utilisateur', 'verbose_name_plural': 'utilisateurs'},
        ),
    ]
