# Generated by Django 5.2.17 on 2026-08-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='titre')),
                ('contenu', models.TextField(blank=True, help_text='Contenu texte du post (vide si le post est un lien ou une image).', verbose_name='contenu')),
                ('url_externe', models.URLField(blank=True, verbose_name='lien externe')),
                ('image_url', models.URLField(blank=True, verbose_name="URL de l'image")),
                ('score', models.IntegerField(default=0, help_text='Somme des votes positifs et négatifs (mise à jour par signaux).', verbose_name='score')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
