# Generated by Django 5.2.17 on 2026-08-09 08:04

from django.db import migrations, models

import core.validateurs


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text="Image importée depuis l'appareil (JPG, PNG, GIF, WebP, 5 Mo max).", upload_to='posts/', validators=[core.validateurs.valider_image_upload], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, verbose_name="URL de l'image distante"),
        ),
    ]
