# Generated by Django 5.2.17 on 2026-08-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_image_alter_post_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_creation',), 'verbose_name': 'publication', 'verbose_name_plural': 'publications'},
        ),
    ]
